//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitedianlan.SqlServer.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLabels_X
    {
        public string XCode { get; set; }
        public string PCode { get; set; }
        public string PName { get; set; }
        public string bzStock { get; set; }
        public string bzPt { get; set; }
        public Nullable<System.DateTime> bzDate { get; set; }
        public string bzPici { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> fhOriginalDate1 { get; set; }
        public Nullable<System.DateTime> fhDate1 { get; set; }
        public string fhAgent1 { get; set; }
        public string fhPt1 { get; set; }
        public string fhStock1 { get; set; }
        public string fhType1 { get; set; }
        public string fhPaper1 { get; set; }
        public string Content1 { get; set; }
        public Nullable<System.DateTime> fhDate2 { get; set; }
        public string fhAgent2 { get; set; }
        public string fhPt2 { get; set; }
        public string fhStock2 { get; set; }
        public string fhType2 { get; set; }
        public string fhPaper2 { get; set; }
        public string Content2 { get; set; }
        public Nullable<System.DateTime> fhDate3 { get; set; }
        public string fhAgent3 { get; set; }
        public string fhPt3 { get; set; }
        public string fhStock3 { get; set; }
        public string fhType3 { get; set; }
        public string fhPaper3 { get; set; }
        public string Content3 { get; set; }
        public string chPt { get; set; }
        public Nullable<System.DateTime> chDate { get; set; }
        public string chAddr { get; set; }
    }
}
