//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitedianlan.SqlServer.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_LabelStorage
    {
        public int ID { get; set; }
        public string QRCode { get; set; }
        public System.DateTime OrderTime { get; set; }
        public System.DateTime OutTime { get; set; }
        public string Dealers { get; set; }
        public string Adminaccount { get; set; }
        public string OutType { get; set; }
        public string OrderNumbels { get; set; }
        public string ExtensionName { get; set; }
        public string ExtensionOrder { get; set; }
    }
}
