//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitedianlan.SqlServer.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_OrderTable
    {
        public int ID { get; set; }
        public string OrderId { get; set; }
        public System.DateTime FinishTime { get; set; }
        public string Accounts { get; set; }
    }
}
