//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitedianlan.SqlServer.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WTDLEntityStrings : DbContext
    {
        public WTDLEntityStrings()
            : base("name=WTDLEntityStrings")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<W_LabelStorage> W_LabelStorage { get; set; }
        public virtual DbSet<tLabels_X> tLabels_X { get; set; }
       // public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<tAgent> tAgents { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<W_OrderTable> W_OrderTable { get; set; }
    }
}
