//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weitedianlan.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public  class Agent : IEntityBase
    {
        public int Id { get; set; }
        public string AID { get; set; }
        public string AName { get; set; }
        public string? AProvince { get; set; }
        public string? ACity { get; set; }
        public string? AAddr { get; set; }
        public string? ATel { get; set; }
        public string? APeople { get; set; }
        public string? ABelong { get; set; }
        public int? AType { get; set; }
        
        public DateTime? datetiem { get; set; }

        ///// <summary>
        ///// 参加活动的ID
        ///// </summary>
        //public int? LotteryActivityId { get; set; }
        
        ///// <summary>
        ///// 参加活动信息
        ///// </summary>
        //public virtual LotteryActivity LotteryActivity { get; set; }

        //  public virtual ICollection<W_LabelStorage> WLabelStorage { get; set; }
    }
}
